name: CI do FrontEnd

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Configurações Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configurações pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
          run_install: false

      - name: Instalar dependências
        run: pnpm install

      - name: Rodar testes
        run: pnpm test

      - name: Prebuild do Android
        run: pnpm expo prebuild --platform android
        env:
          EXPO_PUBLIC_FACEBOOK_APP_ID: ${{ secrets.EXPO_PUBLIC_FACEBOOK_APP_ID }}
          EXPO_PUBLIC_FACEBOOK_CLIENT_TOKEN: ${{ secrets.EXPO_PUBLIC_FACEBOOK_CLIENT_TOKEN }}
